export const mockRoles = [
  { id: 1, name: "Administrador" },
  { id: 2, name: "Empleado" },
  { id: 3, name: "Farmacéutico" },
];

export const mockUsers = [
  {
    id: 1,
    username: "admin",
    password_hash: "hashed_password_1",
    full_name: "Juan Pérez",
    phone: "555-1234",
    address: "Calle Falsa 123, Ciudad",
    role_id: 1,
    status: true,
    created_at: "2023-01-15T10:00:00Z",
  },
  {
    id: 2,
    username: "empleado1",
    password_hash: "hashed_password_2",
    full_name: "María García",
    phone: "555-5678",
    address: "Avenida Siempre Viva 456, Pueblo",
    role_id: 2,
    status: true,
    created_at: "2023-02-20T11:30:00Z",
  },
  {
    id: 3,
    username: "farmaceutico",
    password_hash: "hashed_password_3",
    full_name: "Carlos Ruiz",
    phone: "555-9012",
    address: "Plaza Mayor 789, Villa",
    role_id: 3,
    status: true,
    created_at: "2023-03-01T09:15:00Z",
  },
  {
    id: 4,
    username: "empleado2",
    password_hash: "hashed_password_4",
    full_name: "Ana López",
    phone: "555-3456",
    address: "Calle del Sol 101, Ciudad",
    role_id: 2,
    status: false,
    created_at: "2023-04-10T14:00:00Z",
  },
  {
    id: 5,
    username: "supervisor",
    password_hash: "hashed_password_5",
    full_name: "Pedro Martínez",
    phone: "555-7890",
    address: "Bulevar de la Luna 202, Pueblo",
    role_id: 1,
    status: true,
    created_at: "2023-05-05T16:45:00Z",
  },
  {
    id: 6,
    username: "tecnico",
    password_hash: "hashed_password_6",
    full_name: "Sofía Hernández",
    phone: "555-2345",
    address: "Callejón del Gato 303, Villa",
    role_id: 2,
    status: true,
    created_at: "2023-06-12T08:00:00Z",
  },
  {
    id: 7,
    username: "recepcionista",
    password_hash: "hashed_password_7",
    full_name: "Diego Sánchez",
    phone: "555-6789",
    address: "Avenida Central 404, Ciudad",
    role_id: 2,
    status: true,
    created_at: "2023-07-21T13:00:00Z",
  },
  {
    id: 8,
    username: "contable",
    password_hash: "hashed_password_8",
    full_name: "Laura Díaz",
    phone: "555-0123",
    address: "Ronda del Río 505, Pueblo",
    role_id: 1,
    status: true,
    created_at: "2023-08-01T10:00:00Z",
  },
  {
    id: 9,
    username: "practicante",
    password_hash: "hashed_password_9",
    full_name: "Miguel Torres",
    phone: "555-4567",
    address: "Calle de la Paz 606, Villa",
    role_id: 2,
    status: false,
    created_at: "2023-09-09T11:00:00Z",
  },
  {
    id: 10,
    username: "gerente",
    password_hash: "hashed_password_10",
    full_name: "Isabel Vargas",
    phone: "555-8901",
    address: "Paseo de las Flores 707, Ciudad",
    role_id: 1,
    status: true,
    created_at: "2023-10-18T15:00:00Z",
  },
];

export const mockProviders = [
  {
    id: 1,
    name: "Distribuidora Farmacéutica S.A.",
    nit: "900123456-7",
    phone: "555-1111",
    address: "Av. Principal 100, Ciudad Capital",
  },
  {
    id: 2,
    name: "Laboratorios Salud Total Ltda.",
    nit: "800987654-3",
    phone: "555-2222",
    address: "Calle de la Ciencia 20, Zona Industrial",
  },
  {
    id: 3,
    name: "Medicamentos Express C.A.",
    nit: "700555444-1",
    phone: "555-3333",
    address: "Blvd. Los Remedios 50, Centro",
  },
  {
    id: 4,
    name: "Insumos Médicos del Sur",
    nit: "600333222-9",
    phone: "555-4444",
    address: "Carrera 45 #12-34, Barrio Nuevo",
  },
  {
    id: 5,
    name: "Farmaco Global S.R.L.",
    nit: "500777888-5",
    phone: "555-5555",
    address: "Diagonal 7 #8-90, El Prado",
  },
  {
    id: 6,
    name: "Química Pura Ltda.",
    nit: "400111222-0",
    phone: "555-6666",
    address: "Callejón del Químico 1, Parque Industrial",
  },
  {
    id: 7,
    name: "Distribuciones Vitales",
    nit: "300999888-7",
    phone: "555-7777",
    address: "Av. La Salud 300, Zona Médica",
  },
  {
    id: 8,
    name: "Productos Farmacéuticos del Norte",
    nit: "200444555-2",
    phone: "555-8888",
    address: "Ruta 5 Km 10, Afueras",
  },
  {
    id: 9,
    name: "Suministros Hospitalarios",
    nit: "100666777-8",
    phone: "555-9999",
    address: "Calle del Hospital 15, Sector Salud",
  },
  {
    id: 10,
    name: "Biotech Solutions S.A.",
    nit: "950123789-0",
    phone: "555-0000",
    address: "Parque Tecnológico, Edificio A",
  },
]

export const mockCategories = [
  { id: 1, name: "Analgésicos" },
  { id: 2, name: "Antibióticos" },
  { id: 3, name: "Vitaminas" },
  { id: 4, name: "Antiinflamatorios" },
  { id: 5, name: "Dermatológicos" },
]

export const mockPresentations = [
  { id: 1, name: "Tabletas" },
  { id: 2, name: "Cápsulas" },
  { id: 3, name: "Jarabe" },
  { id: 4, name: "Crema" },
  { id: 5, name: "Inyectable" },
]

export const mockProducts = [
  {
    id: 1,
    code: "PROD001",
    name: "Paracetamol 500mg",
    category_id: 1,
    presentation_id: 1,
    unit: "Caja",
    price: 5.5,
    descuento: 0.5,
    stock: 120,
    stock_min: 50,
    description: "Analgésico y antipirético para aliviar el dolor y la fiebre.",
    created_at: "2023-01-01T10:00:00Z",
  },
  {
    id: 2,
    code: "PROD002",
    name: "Amoxicilina 250mg/5ml",
    category_id: 2,
    presentation_id: 3,
    unit: "Frasco",
    price: 12.75,
    descuento: 0.0,
    stock: 30,
    stock_min: 20,
    description: "Antibiótico de amplio espectro para infecciones bacterianas.",
    created_at: "2023-01-05T11:30:00Z",
  },
  {
    id: 3,
    code: "PROD003",
    name: "Vitamina C 1000mg",
    category_id: 3,
    presentation_id: 2,
    unit: "Frasco",
    price: 8.2,
    descuento: 0.8,
    stock: 80,
    stock_min: 30,
    description: "Suplemento vitamínico para fortalecer el sistema inmune.",
    created_at: "2023-01-10T09:00:00Z",
  },
  {
    id: 4,
    code: "PROD004",
    name: "Ibuprofeno 400mg",
    category_id: 4,
    presentation_id: 1,
    unit: "Blíster",
    price: 7.0,
    descuento: 0.0,
    stock: 40,
    stock_min: 50, // Stock bajo
    description: "Antiinflamatorio no esteroideo para dolor y fiebre.",
    created_at: "2023-01-15T14:00:00Z",
  },
  {
    id: 5,
    code: "PROD005",
    name: "Crema Hidratante 200g",
    category_id: 5,
    presentation_id: 4,
    unit: "Tubo",
    price: 15.0,
    descuento: 1.5,
    stock: 60,
    stock_min: 25,
    description: "Crema para hidratación profunda de la piel seca.",
    created_at: "2023-01-20T16:00:00Z",
  },
  {
    id: 6,
    code: "PROD006",
    name: "Omeprazol 20mg",
    category_id: 1, // Ejemplo de otra categoría si existiera (ej. Gastrointestinales)
    presentation_id: 2,
    unit: "Caja",
    price: 9.99,
    descuento: 0.0,
    stock: 90,
    stock_min: 40,
    description: "Inhibidor de la bomba de protones para acidez estomacal.",
    created_at: "2023-02-01T08:00:00Z",
  },
  {
    id: 7,
    code: "PROD007",
    name: "Termómetro Digital",
    category_id: 5, // Ejemplo de otra categoría si existiera (ej. Dispositivos Médicos)
    presentation_id: 1, // No aplica directamente, pero se usa para el ejemplo
    unit: "Unidad",
    price: 25.0,
    descuento: 2.0,
    stock: 15,
    stock_min: 10,
    description: "Termómetro para medición rápida y precisa de la temperatura corporal.",
    created_at: "2023-02-10T10:00:00Z",
  },
  {
    id: 8,
    code: "PROD008",
    name: "Alcohol Antiséptico 70%",
    category_id: 5, // Ejemplo de otra categoría (ej. Antisépticos)
    presentation_id: 3, // No aplica directamente, pero se usa para el ejemplo
    unit: "Frasco",
    price: 3.2,
    descuento: 0.0,
    stock: 200,
    stock_min: 100,
    description: "Solución antiséptica para desinfección de piel y superficies.",
    created_at: "2023-02-15T12:00:00Z",
  },
  {
    id: 9,
    code: "PROD009",
    name: "Vendas Elásticas",
    category_id: 5, // Ejemplo de otra categoría (ej. Primeros Auxilios)
    presentation_id: 1, // No aplica directamente, pero se usa para el ejemplo
    unit: "Unidad",
    price: 4.5,
    descuento: 0.0,
    stock: 70,
    stock_min: 30,
    description: "Vendas elásticas para soporte y compresión en lesiones.",
    created_at: "2023-02-20T14:00:00Z",
  },
  {
    id: 10,
    code: "PROD010",
    name: "Jarabe para la Tos",
    category_id: 1, // Ejemplo de otra categoría (ej. Respiratorios)
    presentation_id: 3,
    unit: "Frasco",
    price: 9.0,
    descuento: 0.9,
    stock: 25,
    stock_min: 15,
    description: "Jarabe para aliviar la tos seca y con flemas.",
    created_at: "2023-02-25T16:00:00Z",
  },
]
